### ISSUE TITLE
Refactor Imports, Folder Structure, and Use Absolute Paths

### ISSUE THREAD

**Issue by Obskurath** [NicoAlvarado10/NicoUI#3]
To improve the maintainability and scalability of the project, we should refactor the folder structure by grouping related components and creating dedicated folders for shared components. Additionally, we should refactor the import statements to use absolute paths instead of relative ones, as this will enhance readability and reduce the complexity of deep imports.

If you assign me i will do it

**Comment by NicoAlvarado10** [comment]
Hola, gracias por tu propuesta! Me parece una excelente idea mejorar la estructura de carpetas y usar rutas absolutas. Te encargo esta tarea. Por favor, documenta los cambios y realiza pruebas.

Gracias por tu contribución. Saludos.

**Comment by Obskurath** [comment]
Okay, i will get to work on it in some hours
